### ISSUE TITLE
US: Selections

### ISSUE THREAD

**Issue by haxxmaxx** [qlik-oss/sn-table#2]
Make sure you can make selections in the table, storing them and communicating with back-end

tasks:
- [x] #33 send selections to engine
- [x] #34 color cells when selections are active
- [x] #35 selections toolbar
- [x] #51 toggle select one value with cmd/ctrl
- [x] #52 disable selections when not applicable
- [x] #62  Improve selections performance
