### ISSUE TITLE
US: Accessibility

### ISSUE THREAD

**Issue by haxxmaxx** [qlik-oss/sn-table#3]
Most work will likely be implementing keyboard navigation. Since we are using a DOM table element, most screen readers will be there by default.

Tasks:

- [x] #7 Use arrow keys to navigate between cells
- [x] #9 Selections with keys
- [x] #11 Screen readers
- [x] #128 use space/enter to change sorting
- [x] #130 keyboard shortcuts to go to next and previous page
- [x] #131 click to focus table
- [x] #146 Handle keeping focus on cancel/confirm
