### ISSUE TITLE
US: Consume client properties

### ISSUE THREAD

**Issue by haxxmaxx** [qlik-oss/sn-table#5]
Should be able to consume properties we implement using the old properties structure, the add the ability to change properties in nebula (or w/e) with a slightly different structure

- [x] #80 styling panel font size
- [x] #81 styling panel color
- [x] #82 styling panel hover
- [x] #83 column conditional coloring
- [x] #84 column hide/show
- [x] #85 colunm alignment
- [x] #120 auto color fonts when background is set
